### ISSUE TITLE
Do no store JWT in localstorage

### ISSUE THREAD

**Issue by Tbaut** [Tbaut/governance-platform#13]
- store JWT in memory
- Use the "refresh" token stored in a server cookie

Follow the best practices as explained here https://blog.hasura.io/best-practices-of-using-jwt-with-graphql/

**Comment by Tbaut** [comment]
Reading thoroughly the comments http://disq.us/p/24lvpw2. Local storage is not worst than in memory against XSS since the JS memory can be read..

**Comment by niklabh** [comment]
Agree

**Comment by Tbaut** [comment]
Cool, then we can keep that, it's also much simpler to manage multi-tabs :)
